import questMetadata from "./json/questsFromHtmlMeta.json" assert { type: "json" };
import { type Quest } from "../types";

// The metadata is generated by scripts/generate-quest-metadata.mjs to avoid bundling
// raw HTML during the Vite build (which exhausts memory limits in resource-limited
// environments). Run `npm run generate:quests` if the archived quest HTML changes.
export const questsFromHtml: Quest[] = questMetadata satisfies Quest[];
